diaries/urls.py
import imp
from nturl2path import url2pathname
from urllib.parse import urlparse
from django.urls import URLPattern, path
from .import views

app_name = 'diaries'

urlpatterns = [
    path('', views.top, name = 'top')
]

myprofile/urls.py
from django.urls import path
from . import views


app_name = 'myprofile'

urlpatterns = [
    path('', views.top, name = 'top'),
    path('resume/', views.resume, name = 'resume'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('', include('myprofile.urls')),
]

reviews/urls.py
import imp
from site import abs_paths
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.review_list, name = 'review_list'),
    path('detail/<int:pk>/', views.review_detail, name='review_detail'),
    path('create/', views.review_create, name='review_create'),
    path('create/send/', views.review_create_send, name='review_create_send'),
]

diaries/models.py
import imp
from statistics import mode
from unicodedata import category
from django.db import models
from django.utils import timezone
from numpy import mintypecode

# Create your models here.
class Diary(models.Model):
    category = models.CharField('カテゴリ', max_length=255)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return 'カテゴリ:{} 本文:{}'.format(self.category, self.text[:10])

myprofile/models.py
from django.db import models

# Create your models here.

reviews/models.py
from statistics import mode
from django.db import models
from django.utils import timezone
# Create your models here.

class Review(models.Model):
    STARS = (
        (1, '☆'),
        (2, '☆☆'),
        (3, '☆☆☆'),
        (4, '☆☆☆☆'),
        (5, '☆☆☆☆☆')
    )

    store_name = models.CharField('店名', max_length = 255)
    title = models.CharField('タイトル', max_length = 255)
    text = models.TextField('口コミテキスト', blank = True)
    stars = models.IntegerField('星の数', choices = STARS)
    created_at = models.DateTimeField('作成日', default = timezone.now)

    def __str__(self):
        return self.title

diaries/views.py
from multiprocessing import context
from django.shortcuts import render
from .models import Diary

def top(request):
    context = {
        'diary_list': Diary.objects.all(),
    }
    return render(request, 'diaries/diary_list.html', context)

myprofile/views.py
from email import contentmanager
from multiprocessing import context
from shutil import register_unpack_format
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

def top(request):
    context = {
        'name': 'たろう',
    }
    return render(request, 'myprofile/top.html', context)

def resume(request):
    return render(request, 'myprofile/resume.html')

reviews/views.py
from __future__ import absolute_import
from multiprocessing import context
from django import shortcuts
from django.shortcuts import render
from .models import Review
from django.shortcuts import render , get_object_or_404
from django.shortcuts import render , get_object_or_404, redirect

# Create your views here.
def review_list(request):
    context = {
        'review_list': Review.objects.all().order_by('-created_at'),
    }
    return render(request, 'reviews/review_list.html', context)

def review_detail(request, pk):
    context = {
        'review': get_object_or_404(Review, pk=pk)
    }
    return render(request, 'reviews/review_detail.html', context)

def review_create(request):
    return render(request, 'reviews/review_form.html')

def review_create_send(request):
    name = request.POST.get('store_name')
    print('送信されたデータ→ {}'.format(name))
    return redirect('reviews:review_list')

diaries/templates/diaries/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <title>My Diary</title>
<style>
    * {
        margin: 0;
    }
    body {
        color: #333;
        max-width: 500px;
        margin: 0 auto;
        padding-left: 40px;
        padding-right: 40px;
    }

    body > header {
        color: #999;
        font-size: 40px;
        margin-top: 100px;
        margin-bottom: 50px;
        text-align: center;
    }

    main{
        border-top: solid 1px #ddd;
        padding-top: 40px;
    }

    main > article {
        border-bottom: solid 1px #ddd;
        margin-bottom: 40px;
        padding-bottom: 40px;
    }

    main > article > span.category{
        color: #999;
    }
</style>
</head>
<body>
<header>My Diary</header>
<main>
    {% block content %} {% endblock %}
</main>
</body>
</html>

diaries/templates/diaries/diary_list.html
{% extends 'diaries/base.html' %}

{% block content %}
    {% for diary in diary_list %}
        <article>
            <span class = "category">{{ diary.category }}</span><br>
            <p>{{ diary.text }}</p>
        </article>
    {% endfor %}
{% endblock %}

myprofile/templates/myprofile/base.html
<!DOCUTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<header>Taro's Profile</header>

<nav>
    <a href="{% url 'myprofile:top' %}">TOP</a>
    <a href="{% url 'myprofile:resume' %}">Resume</a>
</nav>

{% block content %}{% endblock %}

myprofile/templates/myprofile/top.html
{% extends 'myprofile/base.html' %}

{% block title %}Taro's Profile{% endblock %}

{% block content %}
    <h1>{{ name }}についての概要</h1>
    <p>東京に住んでいる、40歳になったエンジニアです。</p>

    <h2>趣味</h2>
    <ul>
        <li>映画鑑賞</li>
    </ul>
{% endblock %}

reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8"
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>色んなお店の口コミサイト</title>
    <style>
        * {
            margin: 0;
        }

        body {
            color: #333;
        }

        body > header {
            font-size: 40px;
            background-color: #000;
            color: #fff;
            padding: 10px 30px;
        }

        main {
            margin-top: 20px;
            padding: 0 30px;
        }

        main > h1 {
            margin-bottom: 20px;
        }

        main > article {
            padding: 0 30px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
<header>色んなお店の口コミサイト</header>
<main>
    {% block content %}{% endblock %}
</main>
</body>
</html>

reviews/templates/reviews/review_detail.html
{% extends 'reviews/base.html' %}

{% block content %}
    <article>
        <h1>{{ review.store_name }}</h1>
        <p>{{ review.get_stars_display }} - {{ review.title }}</p>
        {{ review.text | linebreaks }}
    </article>
{% endblock %}

reviews/templates/reviews/review_form.html
{% extends 'reviews/base.html' %}

{% block content %}
    <form action="{% url 'reviews:review_create_send' %}" method="POST">
        <input type="text" name="store_name">
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h1>口コミ一覧</h1>
    {% for review in review_list %}
        <article>
            <h2><a href="{% url 'reviews:review_detail' review.pk %}">{{ review.store_name }}</a></h2>
            <p>{{ review.get_stars_display }} - {{ review.title }} </p>
        </article>
    {% endfor %}
    <a href="{% url 'reviews:review_create' %}">口コミ作成ページへ</a>
{% endblock %}